
export const Videos = [ 
    { "videoId": "video01",
     "title": "Learn React in 30 Minutes", 
     "Video":"https://www.youtube.com/embed/uChhQpHMmXE?si=HZkxpEeKHB8gfhGZ&amp;controls=0",
     "thumbnailUrl":  "https://i.ytimg.com/vi/vIRBSI-elUM/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDcsFqaewJ4Lc5VVITLECwmZnmUGg",
      "description": "A quick tutorial to get startedwith React.",
       "channelId": "channel01", 
     "uploader": "user01",
     "views": 15200,
     "likes": 1023,
    "dislikes": 45, 
    "uploadDate": "2024-09-20",
     "comments": [ { "commentId": "comment01", 
        "userId":"user02", 
        "text": "Great video! Very helpful.", 
        "timestamp": "2024-09-21T08:30:00Z" }] 
  },
  { "videoId": "video02",
    "title": "Learn React in 30 Minutes", 
    "thumbnailUrl":  "https://i.ytimg.com/vi/vIRBSI-elUM/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDcsFqaewJ4Lc5VVITLECwmZnmUGg",
     "description": "A quick tutorial to get startedwith React.",
      "channelId": "channel01", 
      "Video":"https://youtu.be/uChhQpHMmXE?si=vH2YXV129zAR6J8I",
    "uploader": "user01",
    "views": 15200,
    "likes": 1023,
   "dislikes": 45, 
   "uploadDate": "2024-09-20",
    "comments": [ { "commentId": "comment01", 
       "userId":"user02", 
       "text": "Great video! Very helpful.", 
       "timestamp": "2024-09-21T08:30:00Z" }] 
 },
 { "videoId": "video03",
    "title": "Learn React in 30 Minutes", 
    "thumbnailUrl":  "https://i.ytimg.com/vi/vIRBSI-elUM/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDcsFqaewJ4Lc5VVITLECwmZnmUGg",
     "description": "A quick tutorial to get startedwith React.",
      "channelId": "channel01", 
    "uploader": "user01",
    "views": 15200,
    "likes": 1023,
   "dislikes": 45, 
   "uploadDate": "2024-09-20",
    "comments": [ { "commentId": "comment01", 
       "userId":"user02", 
       "text": "Great video! Very helpful.", 
       "timestamp": "2024-09-21T08:30:00Z" }] 
 },
 { "videoId": "video04",
    "title": "Learn React in 30 Minutes", 
    "thumbnailUrl":  "https://i.ytimg.com/vi/vIRBSI-elUM/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDcsFqaewJ4Lc5VVITLECwmZnmUGg",
     "description": "A quick tutorial to get startedwith React.",
      "channelId": "channel01", 
    "uploader": "user01",
    "views": 15200,
    "likes": 1023,
   "dislikes": 45, 
   "uploadDate": "2024-09-20",
    "comments": [ { "commentId": "comment01", 
       "userId":"user02", 
       "text": "Great video! Very helpful.", 
       "timestamp": "2024-09-21T08:30:00Z" }] 
 },
 { "videoId": "video05",
    "title": "Learn React in 30 Minutes", 
    "thumbnailUrl":  "https://i.ytimg.com/vi/vIRBSI-elUM/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDcsFqaewJ4Lc5VVITLECwmZnmUGg",
     "description": "A quick tutorial to get startedwith React.",
      "channelId": "channel01", 
    "uploader": "user01",
    "views": 15200,
    "likes": 1023,
   "dislikes": 45, 
   "uploadDate": "2024-09-20",
    "comments": [ { "commentId": "comment01", 
       "userId":"user02", 
       "text": "Great video! Very helpful.", 
       "timestamp": "2024-09-21T08:30:00Z" }] 
 },
 { "videoId": "video06",
    "title": "Learn React in 30 Minutes", 
    "thumbnailUrl":  "https://i.ytimg.com/vi/vIRBSI-elUM/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDcsFqaewJ4Lc5VVITLECwmZnmUGg",
     "description": "A quick tutorial to get startedwith React.",
      "channelId": "channel01", 
    "uploader": "user01",
    "views": 15200,
    "likes": 1023,
   "dislikes": 45, 
   "uploadDate": "2024-09-20",
    "comments": [ { "commentId": "comment01", 
       "userId":"user02", 
       "text": "Great video! Very helpful.", 
       "timestamp": "2024-09-21T08:30:00Z" }] 
 },
 { "videoId": "video07",
    "title": "Learn React in 30 Minutes", 
    "thumbnailUrl":  "https://i.ytimg.com/vi/vIRBSI-elUM/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDcsFqaewJ4Lc5VVITLECwmZnmUGg",
     "description": "A quick tutorial to get startedwith React.",
      "channelId": "channel01", 
    "uploader": "user01",
    "views": 15200,
    "likes": 1023,
   "dislikes": 45, 
   "uploadDate": "2024-09-20",
    "comments": [ { "commentId": "comment01", 
       "userId":"user02", 
       "text": "Great video! Very helpful.", 
       "timestamp": "2024-09-21T08:30:00Z" }] 
 },
 { "videoId": "video08",
    "title": "Learn React in 30 Minutes", 
    "thumbnailUrl":  "https://i.ytimg.com/vi/vIRBSI-elUM/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDcsFqaewJ4Lc5VVITLECwmZnmUGg",
     "description": "A quick tutorial to get startedwith React.",
      "channelId": "channel01", 
    "uploader": "user01",
    "views": 15200,
    "likes": 1023,
   "dislikes": 45, 
   "uploadDate": "2024-09-20",
    "comments": [ { "commentId": "comment01", 
       "userId":"user02", 
       "text": "Great video! Very helpful.", 
       "timestamp": "2024-09-21T08:30:00Z" }] 
 },
 { "videoId": "video09",
    "title": "Learn React in 30 Minutes", 
    "thumbnailUrl":  "https://i.ytimg.com/vi/vIRBSI-elUM/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDcsFqaewJ4Lc5VVITLECwmZnmUGg",
     "description": "A quick tutorial to get startedwith React.",
      "channelId": "channel01", 
    "uploader": "user01",
    "views": 15200,
    "likes": 1023,
   "dislikes": 45, 
   "uploadDate": "2024-09-20",
    "comments": [ { "commentId": "comment01", 
       "userId":"user02", 
       "text": "Great video! Very helpful.", 
       "timestamp": "2024-09-21T08:30:00Z" }] 
 },
 
  


]
    